name: Teste OIDC AWS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aws-test:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::676617883170:role/GitHubRole
          aws-region: us-east-1

      - name: Testar acesso Ã  AWS
        run: aws sts get-caller-identity
